package com.laplace.api.common.constants.enums;

import java.util.function.Supplier;
import java.util.stream.Stream;

public enum EntityType {
  SETTING("SETTING"),
  SETTING_PROFILE("SETTING_PROFILE"),
  SETTING_NOTIFICATION_SETTING("SETTING_NOTIFICATION_SETTING"),
  CREATE_PROFILE_PAGE("CREATE_PROFILE_PAGE"),
  CPP_DESCRIPTION_IMAGE("CPP_DESCRIPTION_IMAGE"),
  CPP_SEO_ADMINISTRATION("CPP_SEO_ADMINISTRATION"),
  CPP_ASSIGN_CONTENTS("CPP_ASSIGN_CONTENTS"),
  CPP_PUBLISH_PRIVATE_LP("CPP_PUBLISH_PRIVATE_LP"),
  CONTENTS("CONTENTS"),
  APC_GOOD("APC_GOOD"),
  APC_GOOD_TOPS("APC_GOOD_TOPS"),
  APC_GOOD_BOTTOMS("APC_GOOD_BOTTOMS"),
  APC_GOOD_ALL_IN_ONE("APC_GOOD_ALL_IN_ONE"),
  APC_GOOD_OTHERS("APC_GOOD_OTHERS"),
  APC_COORDINATE("APC_COORDINATE"),
  APC_COORDINATE_PHOTO_GOODS("APC_COORDINATE_PHOTO_GOODS"),
  APC_COORDINATE_ONLY_GOODS("APC_COORDINATE_ONLY_GOODS"),
  APC_COORDINATE_ONLY_PHOTO("APC_COORDINATE_ONLY_PHOTO"),
  BORROW_COORDINATE("BORROW_COORDINATE"),
  BORROW_COORDINATE_ONLY_PHOTO("BORROW_COORDINATE_ONLY_PHOTO"),
  BORROW_COORDINATE_ONLY_GOODS("BORROW_COORDINATE_ONLY_GOODS"),
  BORROW_COORDINATE_PHOTO_GOODS("BORROW_COORDINATE_PHOTO_GOODS"),
  APC_NEWS("APC_NEWS"),
  APC_STYLIST("APC_STYLIST"),
  CONNECT_MOVIE("CONNECT_MOVIE"),
  CM_PHOTO_GOODS("CM_PHOTO_GOODS"),
  CM_ONLY_GOODS("CM_ONLY_GOODS"),
  CM_ONLY_PHOTO("CM_ONLY_PHOTO"),
  CM_ACTIVATION_MOVIE("CM_ACTIVATION_MOVIE"),
  ADVERTISE_ADMINISTRATION("ADVERTISE_ADMINISTRATION"),
  AA_GOOD("AA_GOOD"),
  AA_GOOD_TOPS("AA_GOOD_TOPS"),
  AA_GOOD_BOTTOMS("AA_GOOD_BOTTOMS"),
  AA_GOOD_ALL_IN_ONE("AA_GOOD_ALL_IN_ONE"),
  AA_GOOD_OTHERS("AA_GOOD_OTHERS"),
  AA_COORDINATE("AA_COORDINATE"),
  AA_COORDINATE_PHOTO_GOODS("AA_COORDINATE_PHOTO_GOODS"),
  AA_COORDINATE_ONLY_GOODS("AA_COORDINATE_ONLY_GOODS"),
  AA_COORDINATE_ONLY_PHOTO("AA_COORDINATE_ONLY_PHOTO"),
  AA_MOVIE("AA_MOVIE"),
  PACKAGE_ORDER("PACKAGE_ORDER"),
  PACKAGE_PAYMENT("PACKAGE_PAYMENT"),
  REGISTER_POLICY("REGISTER_POLICY"),
  NOTIFICATION("NOTIFICATION"),
  RP_RENTAL("RP_RENTAL"),
  RP_PURCHASE("RP_PURCHASE"),
  BORROWED_CONTENTS("BORROWED_CONTENTS"),
  FUJ_SETTING("FUJ_SETTING"),
  FUJ_SEO_ADMINISTRATION("FUJ_SEO_ADMINISTRATION"),
  FUJ_SA_HOME("FUJ_SA_HOME"),
  FUJ_SA_GOOD_DETAIL("FUJ_SA_GOOD_DETAIL"),
  FUJ_SA_COORDINATE_DETAIL("FUJ_SA_COORDINATE_DETAIL"),
  FUJ_SA_MOVIE_DETAIL("FUJ_SA_MOVIE_DETAIL"),
  FUJ_SA_NEWS("FUJ_SA_NEWS"),
  FUJ_SA_REVIEW("FUJ_SA_REVIEW"),
  FUJ_SA_STYLIST("FUJ_SA_STYLIST"),
  FUJ_CLUSTER_ADMINISTRATION("FUJ_CLUSTER_ADMINISTRATION"),
  FUJ_CA_NORMALIZATION("FUJ_CA_NORMALIZATION"),
  FUJ_CA_NORMALIZATION_01_CLUSTER("FUJ_CA_NORMALIZATION_01_CLUSTER"),
  FUJ_CA_NORMALIZATION_02_CLUSTER("FUJ_CA_NORMALIZATION_02_CLUSTER"),
  FUJ_CA_NORMALIZATION_03_CLUSTER("FUJ_CA_NORMALIZATION_03_CLUSTER"),
  FUJ_CA_NORMALIZATION_04_CLUSTER("FUJ_CA_NORMALIZATION_04_CLUSTER"),
  FUJ_CA_LANDING_PAGE("FUJ_CA_LANDING_PAGE"),
  FUJ_CA_LP_01_CLUSTER("FUJ_CA_LP_01_CLUSTER"),
  FUJ_CA_LP_02_CLUSTER("FUJ_CA_LP_02_CLUSTER"),
  FUJ_CA_LP_03_CLUSTER("FUJ_CA_LP_03_CLUSTER"),
  FUJ_CA_LP_04_CLUSTER("FUJ_CA_LP_04_CLUSTER"),
  FUJ_OCCASION("FUJ_OCCASION"),
  FUJ_OCCASION_NORMALIZATION("FUJ_OCCASION_NORMALIZATION"),
  FUJ_OCCASION_NORMALIZATION_01_OCCASION("FUJ_OCCASION_NORMALIZATION_01_OCCASION"),
  FUJ_OCCASION_NORMALIZATION_02_OCCASION("FUJ_OCCASION_NORMALIZATION_02_OCCASION"),
  FUJ_OCCASION_NORMALIZATION_03_OCCASION("FUJ_OCCASION_NORMALIZATION_03_OCCASION"),
  FUJ_OCCASION_NORMALIZATION_04_OCCASION("FUJ_OCCASION_NORMALIZATION_04_OCCASION"),
  FUJ_OCCASION_NORMALIZATION_05_OCCASION("FUJ_OCCASION_NORMALIZATION_05_OCCASION"),
  FUJ_OCCASION_LANDING_PAGE("FUJ_OCCASION_LANDING_PAGE"),
  FUJ_OCCASION_LP_01_OCCASION("FUJ_OCCASION_LP_01_OCCASION"),
  FUJ_OCCASION_LP_02_OCCASION("FUJ_OCCASION_LP_02_OCCASION"),
  FUJ_OCCASION_LP_03_OCCASION("FUJ_OCCASION_LP_03_OCCASION"),
  FUJ_OCCASION_LP_04_OCCASION("FUJ_OCCASION_LP_04_OCCASION"),
  FUJ_OCCASION_LP_05_OCCASION("FUJ_OCCASION_LP_05_OCCASION"),
  FUJ_CATEGORY_ADMINISTRATION("FUJ_CATEGORY_ADMINISTRATION"),
  FUJ_CATEGORY_ADMINISTRATION_NORMALIZATION("FUJ_CATEGORY_ADMINISTRATION_NORMALIZATION"),
  FUJ_CATEGORY_ADMINISTRATION_NORMALIZATION_01_TOPS(
      "FUJ_CATEGORY_ADMINISTRATION_NORMALIZATION_01_TOPS"),
  FUJ_CATEGORY_ADMINISTRATION_NORMALIZATION_02_BOTTOMS(
      "FUJ_CATEGORY_ADMINISTRATION_NORMALIZATION_02_BOTTOMS"),
  FUJ_CATEGORY_ADMINISTRATION_03_ALL_IN_ONE("FUJ_CATEGORY_ADMINISTRATION_03_ALL_IN_ONE"),
  FUJ_OCCASION_NORMALIZATION_04_OTHERS("FUJ_OCCASION_NORMALIZATION_04_OTHERS"),
  FUJ_AD_ADMINISTRATION("FUJ_AD_ADMINISTRATION"),
  FUJ_AA_HOME("FUJ_AA_HOME"),
  FUJ_AA_HOME_MOVIE("FUJ_AA_HOME_MOVIE"),
  FUJ_AA_HOME_COORDINATE("FUJ_AA_HOME_COORDINATE"),
  FUJ_AA_HOME_COORDINATE_GOOD_PHOTO("FUJ_AA_HOME_COORDINATE_GOOD_PHOTO"),
  FUJ_AA_HOME_COORDINATE_ONLY_GOODS("FUJ_AA_HOME_COORDINATE_ONLY_GOODS"),
  FUJ_AA_HOME_COORDINATE_ONLY_PHOTO("FUJ_AA_HOME_COORDINATE_ONLY_PHOTO"),
  FUJ_AA_HOME_NEWS("FUJ_AA_HOME_NEWS"),
  FUJ_AA_HOME_STYLIST("FUJ_AA_HOME_STYLIST"),
  FUJ_AA_HOME_GOOD("FUJ_AA_HOME_GOOD"),
  FUJ_AA_HOME_GOOD_TOPS("FUJ_AA_HOME_GOOD_TOPS"),
  FUJ_AA_HOME_GOOD_BOTTOMS("FUJ_AA_HOME_GOOD_BOTTOMS"),
  FUJ_AA_HOME_GOOD_ALL_IN_ONE("FUJ_AA_HOME_GOOD_ALL_IN_ONE"),
  FUJ_AA_HOME_GOOD_OTHERS("FUJ_AA_HOME_GOOD_OTHERS"),
  FUJ_IMPORT_CSV("FUJ_IMPORT_CSV"),
  FUJ_IMPORT_CSV_ANA_HOTEL("FUJ_IMPORT_CSV_ANA_HOTEL"),
  FUJ_HISTORY("FUJ_HISTORY"),
  FUJ_HISTORY_PAYMENT("FUJ_HISTORY_PAYMENT"),
  FUJ_HISTORY_ORDER("FUJ_HISTORY_ORDER"),
  FUJ_DOCUMENT("FUJ_DOCUMENT"),
  FUJ_DOCUMENT_TERMS_OF_SERVICE("FUJ_DOCUMENT_TERMS_OF_SERVICE"),
  FUJ_DOCUMENT_PRIVACY_POLICY("FUJ_DOCUMENT_PRIVACY_POLICY"),
  FUJ_DOCUMENT_FAQ("FUJ_DOCUMENT_FAQ"),
  FUJ_DOCUMENT_SPECIFIED_COMMERCIAL_TRANSACTION_LAW(
      "FUJ_DOCUMENT_SPECIFIED_COMMERCIAL_TRANSACTION_LAW"),
  FUJ_DOCUMENT_COPYRIGHT_INFORMATION("FUJ_DOCUMENT_COPYRIGHT_INFORMATION"),
  FUJ_DOCUMENT_HELP("FUJ_DOCUMENT_HELP"),
  FUJ_INVITATION_PACKAGE("FUJ_INVITATION_PACKAGE"),
  FUJ_IMPORT_CSV_AFFILIATE_CSV("FUJ_IMPORT_CSV_AFFILIATE_CSV"),
  FUJ_IMPORT_CSV_ANA_HOTEL_VIEW("FUJ_IMPORT_CSV_ANA_HOTEL_VIEW");

  private final String entityName;

  EntityType(String entityName) {
    this.entityName = entityName;
  }

  /**
   * Returns EntityType for given name
   *
   * @param name name of the EntityType
   * @return EntityType representing given name;
   */
  public static EntityType forName(String name) {
    return entitiesSupplier().get().filter(entityType -> entityType.entityName.equals(name))
        .findFirst()
        .orElseThrow(
            () -> new IllegalArgumentException("Cannot create enum from " + name + " value!"));
  }

  private static Supplier<Stream<EntityType>> entitiesSupplier() {
    return () -> Stream.of(EntityType.values());
  }

  public String getEntityName() {
    return entityName;
  }
}
