package com.laplace.api.common.constants.enums;

public enum RequestStatus {
  PUBLISHING,
  PUBLISHED,
  PUBLISH_REQUESTED,
  PUBLISH_REQUEST_EXPIRED,
  PUBLISH_REQUEST_REJECTED,
  PUBLISH_REQUEST_DEACTIVATED,
  BORROWING,
  BORROWED,
  BORROW_REQUESTED,
  BORROW_REQUEST_DEACTIVATED,
  BORROW_REQUEST_REJECTED,
  BORROW_REQUEST_EXPIRED,
  NOT_REQUESTED
}